// nolint
// autogenerated code using github.com/rigelrozanski/multitool
// aliases generated for the following subdirectories:
// ALIASGEN: github.com/netcloth/netcloth-chain/modules/crisis/types
package crisis

import (
	"github.com/netcloth/netcloth-chain/modules/crisis/internal/keeper"
	"github.com/netcloth/netcloth-chain/modules/crisis/internal/types"
)

const (
	ModuleName           = types.ModuleName
	DefaultParamspace    = types.DefaultParamspace
	EventTypeInvariant   = types.EventTypeInvariant
	AttributeValueCrisis = types.AttributeValueCrisis
	AttributeKeyRoute    = types.AttributeKeyRoute
)

var (
	RegisterCodec            = types.RegisterCodec
	ErrNoSender              = types.ErrNoSender
	ErrUnknownInvariant      = types.ErrUnknownInvariant
	NewGenesisState          = types.NewGenesisState
	DefaultGenesisState      = types.DefaultGenesisState
	NewMsgVerifyInvariant    = types.NewMsgVerifyInvariant
	ParamKeyTable            = types.ParamKeyTable
	NewInvarRoute            = types.NewInvarRoute
	NewKeeper                = keeper.NewKeeper
	ModuleCdc                = types.ModuleCdc
	ParamStoreKeyConstantFee = types.ParamStoreKeyConstantFee
)

type (
	GenesisState       = types.GenesisState
	MsgVerifyInvariant = types.MsgVerifyInvariant
	InvarRoute         = types.InvarRoute
	Keeper             = keeper.Keeper
)
