// nolint
// autogenerated code using github.com/rigelrozanski/multitool
// aliases generated for the following subdirectories:
// ALIASGEN: github.com/netcloth/netcloth-chain/modules/mint/internal/keeper
// ALIASGEN: github.com/netcloth/netcloth-chain/modules/mint/internal/types
package mint

import (
	"github.com/netcloth/netcloth-chain/modules/mint/internal/keeper"
	"github.com/netcloth/netcloth-chain/modules/mint/internal/types"
)

const (
	ModuleName            = types.ModuleName
	DefaultParamspace     = types.DefaultParamspace
	StoreKey              = types.StoreKey
	QuerierRoute          = types.QuerierRoute
	QueryParameters       = types.QueryParameters
	QueryInflation        = types.QueryInflation
	QueryAnnualProvisions = types.QueryAnnualProvisions
)

var (
	// functions aliases
	NewKeeper           = keeper.NewKeeper
	NewQuerier          = keeper.NewQuerier
	NewGenesisState     = types.NewGenesisState
	DefaultGenesisState = types.DefaultGenesisState
	ValidateGenesis     = types.ValidateGenesis
	ParamKeyTable       = types.ParamKeyTable
	NewParams           = types.NewParams
	DefaultParams       = types.DefaultParams

	// variable aliases
	ModuleCdc             = types.ModuleCdc
	KeyMintDenom          = types.KeyMintDenom
	KeyInflationRate      = types.KeyInflationRate
	KeyNextInflateHeight  = types.KeyNextInflateHeight
	KeyBlockProvision     = types.KeyBlockProvision
	KeyBlocksPerYear      = types.KeyBlocksPerYear
	KeyTotalSupplyCeiling = types.KeyTotalSupplyCeiling
)

type (
	Keeper       = keeper.Keeper
	GenesisState = types.GenesisState
	Params       = types.Params
)
